import Navbar from './Navbar';
import Hero from './Hero';
import PopularCourses from './PopularCourses';
import SuperQuality from './SuperQuality';
import Services from './Services';
import CustomerReviews from './CustomerReviews';
import Subscribe from './Subscribe';
import Footer from './Footer';
import Contact from './Contact';
import Sidebar from './Sidebar';
import Topbar from './Topbar';
import DashHeader from './DashHeader';
import Insights from './Insights';
import NewUsers from './NewUsers';
import Reminders from './Reminders';
import AddUser from './AddUser';
import Pagination from './Pagination'
import Reaction from './Reaction';
export {Navbar,Reaction, Hero, PopularCourses, SuperQuality, Services, CustomerReviews, Subscribe, Footer, Sidebar, Topbar, DashHeader, Insights, NewUsers, Reminders,AddUser}